//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int HotelID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        
        [Display(Name = "Max Capacity")]
        public int MaxCapacity { get; set; }
        
        [Display(Name = "Street Address")]
        public string StreetAddress { get; set; }

        [Display(Name = "City Address")]
        public string CityAddress { get; set; }

        [Display(Name = "State Address")]
        public string StateAddress { get; set; }

        [Display(Name = "Country Address")]
        public string CountryAddress { get; set; }

        [Display(Name = "ZIP Address")]
        public string ZIPAddress { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone")]
        public string Phone { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
