//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveIt.Models
{
    using System;
    using System.Collections.Generic;
<<<<<<< Updated upstream
    using System.ComponentModel.DataAnnotations;

=======
    
>>>>>>> Stashed changes
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoomID { get; set; }
<<<<<<< Updated upstream

        [Required(ErrorMessage = "Please specify a check in date")]
        [Display(Name = "Check In Date")]
        [DataType(DataType.Date)]
        public System.DateTime CheckIn { get; set; }

        [Display(Name = "Length of Stay")]
        public Nullable<int> StayLength { get; set; }

        [Required(ErrorMessage = "Please specify a check out date")]
        [Display(Name = "Check In Date")]
        [DataType(DataType.Date)]
        public System.DateTime CheckOut { get; set; }

        [Display(Name = "Nightly Rate")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> NightlyRate { get; set; }

=======
        public System.DateTime CheckIn { get; set; }
        public Nullable<int> StayLength { get; set; }
        public System.DateTime CheckOut { get; set; }
        public Nullable<decimal> NightlyRate { get; set; }
    
>>>>>>> Stashed changes
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
