//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReserveIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public string RoomTypeID { get; set; }
        public string RoomTypeDescription { get; set; }
        public int MaxOccupancy { get; set; }
    }
}
